#!/bin/bash

# Build a new fidion apk
# Params:
# 	- App flavor (see list of case-statements below).
#	- These must be prefixed with a '-' and can be combined
#	  (e.g. -bri to build a release apk and deploy it to the device).
#		b -> Build new apk
#		i -> Deploy apk to device
#		r -> Use release apk
#		d -> Uninstall existing apk
#		u -> Uplad apk to crashlytics
#		v -> Discard version code changes
#

flavor="invalid"
build=false
variant="debug"
deploy=false
upload=false
delete=false

if [[ $# == 0 ]]; then
	exit 1
fi

for var in "$@"
do
	if [[ ${var:0:1} == "-" ]]; then
		if [[ $var == *"b"* ]]; then
			build=true;
    		printf "****** Build new apk\n";
		fi
		if [[ $var == *"r"* ]]; then
			variant="release";
    		printf "****** Build variant: Release\n";
		fi
		if [[ $var == *"d"* ]]; then
	    	delete=true;
			printf "****** Delete existing apk \n";
		fi
		if [[ $var == *"i"* ]]; then
	    	deploy=true;
	    	printf "****** Install to device\n";
	    fi
		if [[ $var == *"u"* ]]; then
	    	upload=true;
			printf "****** Upload to crashlytics\n";
		fi
		if [[ $var == *"v"* ]]; then
	    	git checkout -- app/config/versioncode/versioncode.properties
			printf "****** Version code changes have been discarded\n";
		fi
	else
		flavor=$var;
	fi
done

if [[ $flavor == "invalid" ]]; then
	printf "****** No flavor param found, abortin\gn"
	exit 1;
fi

case $flavor in
fidion)
	appId="de.fcms.webapp.mywebapp"
	;;
fidion_kathrin)
	appId="de.fcms.webapp.kathrin.testapp"
	;;
luzern)
	appId="de.fcms.webapp.luzernerzeitung"
	;;
sk_epaper)
	appId="com.sk.de"
	;;
oon)
	appId="de.fcms.webapp.oon"
	;;
bote)
	appId="com.soxes.bote"
	;;
fnp)
	appId="de.fcms.webapp.fnp"
	;;
frankenpost)
	appId="de.fcms.webapp.fp"
	;;
vaterland)
	appId="de.fcms.webapp.vaterland"
	;;
in_sued)
	appId="de.fcms.webapp.is"
	;;
np)
	appId="de.fcms.webapp.np"
	;;
heidenheim)
	appId="de.fcms.webapp.hz"
	;;
tagblatt)
	appId="de.fcms.webapp.tagblatt"
	;;
volksfreund)
	appId="de.fcms.webapp.volksfreund"
	;;
ka_news)
	appId="de.fcms.webapp.ka.news"
	;;
sk_news)
	appId="de.fcms.webapp.sk_news"
	;;
filmtage)
	appId="de.fcms.webapp.filmtage"
	;;
mp_news)
	appId="de.fcms.webapp.mp.news"
	;;
fnp_news)
	appId="de.fcms.webapp.fnp.news"
	;;
dk_epaper)
	appId="de.fcms.webapp.dk.epaper"
	;;
me_epaper)
	appId="de.fcms.webapp.mainecho"
	;;
gaz)
	appId="de.fcms.webapp.mdv.gaz"
	;;
aaz)
	appId="de.fcms.webapp.mdv.aaz"
	;;
wz)
	appId="de.fcms.webapp.mdv.wz"
	;;
esac

Flavor="$(tr '[:lower:]' '[:upper:]' <<< ${flavor:0:1})${flavor:1}"
Variant="$(tr '[:lower:]' '[:upper:]' <<< ${variant:0:1})${variant:1}"

if [[ $build == true ]]; then
	gradlew --project-prop appId=$appId --stacktrace clean assemble$Flavor$Variant
fi

if [[ $delete == true ]]; then
	echo Uninstalling ./app/build/outputs/apk/app-$flavor-$variant.apk
	gradlew uninstall$Flavor"Release" uninstall$Flavor"Debug"
fi

if [[ $deploy == true ]]; then
	echo Installing ./app/build/outputs/apk/app-$flavor-$variant.apk
	gradlew install$Flavor$Variant
fi

if [[ $upload == true ]]; then
	echo Distributing $Flavor"Release" to crashlytics.
	gradlew crashlyticsUploadDistribution$Flavor"Release"
	echo Done.
fi