#!/bin/bash

if [[ $1 == "test" ]]
then
    ./gradlew clean testFidionDebugUnitTest
elif [[ $1 == "style" ]]
then
    ./gradlew clean checkstyle
elif [[ $1 == "bugs" ]]
then
    ./gradlew clean check
else
    ./gradlew clean testFidionDebugUnitTest checkstyle check
fi
