#!/bin/bash

# Gradle helper script
# Params:
# 	- App flavor.
#	- These must be prefixed with a '-' and can be combined
#	  (e.g. -bri to build a release apk and deploy it to the device).
#		b -> Build new apk
#		i -> Install apk to device
#		r -> Use release apk
#		d -> Uninstall existing apk
#

flavor=""
build=false
variant="debug"
deploy=false
delete=false

for var in "$@"
do
	if [[ ${var:0:1} == "-" ]]; then
		if [[ $var == *"b"* ]]; then
			build=true;
    		printf "****** Build new apk\n";
		fi
		if [[ $var == *"r"* ]]; then
			variant="release";
    		printf "****** Build variant: Release\n";
		fi
		if [[ $var == *"d"* ]]; then
	    	delete=true;
			printf "****** Delete existing apk \n";
		fi
		if [[ $var == *"i"* ]]; then
	    	deploy=true;
	    	printf "****** Install to device\n";
	    fi
	else
		flavor=$var;
	fi
done

if [[ $build == true ]]; then
	gradlew assemble$Flavor$Variant
fi

if [[ $delete == true ]]; then
	if [[ $flavor != true ]]; then
		echo Uninstalling ./app/build/outputs/apk/app-$flavor-$variant.apk
		gradlew uninstall$Flavor"Release" uninstall$Flavor"Debug"
	else
		echo Uninstalling all app flavors
		gradlew uninstallAll
	fi
fi

if [[ $deploy == true ]]; then
	echo Installing ./app/build/outputs/apk/app-$flavor-$variant.apk
	adb install -r ./app/build/outputs/apk/app-$flavor-$variant.apk
fi