#!/bin/bash

prompt()
{
	echo "Undo changes by resetting last commit? (y/n)"
	read -rsn1 response
	if [ "$response" == "y" ]; then
		hashOfPreviousCommit=$(git rev-parse HEAD~1)
        git reset --mixed $hashOfPreviousCommit;
		
        echo "Done."
	elif [ "$response" == "n" ]; then
		echo "Aborted."
		exit 1
	else
		prompt
	fi
}

prompt
