#!/bin/bash

# Checkout dev branch, fetch & pull, create new ticket with the given #number

((!$#)) && echo No branch name, command ignored! && exit 1

git checkout dev && git fetch && git pull && git checkout -b ticket/$1