#!/bin/bash

# Remove branch locally and on origin.

((!$#)) && echo No branch name, command ignored! && exit 1

for var in "$@"
do
    if [[ !($var =~ \*|master|slave|dev|release) ]]; then
    	branch=$var;
    	if [[ $var =~ ^?[0-9]+$ ]]; then
    		branch="ticket/"$var;
    	fi

		git branch -d $branch;
    	git push origin --delete $branch;
    else
		echo "Won\'t remove $var, as its name contains *|master|slave|dev|release".
    fi
done