#!/bin/bash

# This script helps to commit staged changes.

branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p');
commitType="refs"
message=""

# Get ticketNumber by removing 'ticket/' from the branch's name.
# Probably could be improved, to get everything after the last slash.
ticketNumber=${branch:7};

# If three params are passed:
if [ "$#" -eq 3 ]; then
    # $1: ticketNo, $2: EH|RF|BF|BF, $3: Commit message
    ticketNumber=$1
    commitType=$2
    message=$3

# If two params are passed
elif [ "$#" -eq 2 ]; then
    # $1: ticketNo, $2: Commit message
    ticketNumber=$1
    message=$2

# If one param is passed
elif [ "$#" -eq 1 ]; then
    # $1: Commit message;
    # ticketNo is computed automatically. Only use this with branch names that fit the 'ticket/#'-pattern
    if [ -z "$ticketNumber" ]; then
        echo "No ticket number present, aborting!";
    else
        message=$1
    fi
else
    echo "Illegal number of parameters";
fi

if [ -z "$ticketNumber" ]; then
        echo "No ticket number present, aborting!";
elif [ -z "$message" ]; then
        echo "No commit message present, aborting!";
else
    git commit -m "[$commitType #$ticketNumber] $message";
fi
