#!/bin/bash

# Fetch & pull on current branch, checkout 'sprint/$1', create  new branch 'ticket/$2'

((!$#)) && echo No branch name, command ignored! && exit 1

git checkout sprint/$1 && git fetch && git pull && git checkout -b ticket/$2

echo -e "\e[33m***** Stop tracking in planio? [Y, n]"
read -rsn1 stop
if [ "$stop" == "y" ]; then
    opn https://webfactor.plan.io/stop_timer
fi

echo -e "\e[33m***** Start tracking in planio? [Y, n]"
read -rsn1 start
if [ "$start" == "y" ]; then
    opn https://webfactor.plan.io/issues/$2/start_timer
fi
