#!/bin/bash

# This script helps to commit staged changes.

branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p');
commitType="refs"
message=""
ticketNumber=""

# Get ticketNumber by removing 'ticket/' from the branch's name,
# if branch name begins with "ticket/"
if [[ ${branch:0:7} == "ticket/" ]]; then
	ticketNumber=${branch//[!0-9]/};
fi

# If three params are passed:
if [ "$#" -eq 3 ]; then
    # $1: ticketNo, $2: EH|RF|BF|BF, $3: Commit message
    ticketNumber=$1
    commitType=$2
    message=$3

# If two params are passed
elif [ "$#" -eq 2 ]; then
    # $1: ticketNo, $2: Commit message
    ticketNumber=$1
    message=$2

# If one param is passed
elif [ "$#" -eq 1 ]; then
    # $1: Commit message;
    # ticketNo is computed automatically. Only use this with branch names that fit the 'ticket/#'-pattern
    message=$1
else
    echo "Illegal number of parameters";
fi

if [ -z "$ticketNumber" ] ; then
	echo "No ticket number, aborting!";
elif [[ $ticketNumber =~ ^?[0-9]+$ ]]; then
	echo "Malformed ticket number, aborting!";
elif [ -z "$message" ]; then
    echo "No commit message, aborting!";
else
    git commit -m "[$commitType #$ticketNumber] $message";
fi
