#!/bin/bash

# Merge branch to dev branch and delete it afterwards
# If ticket number is parsed as param, try to merge ticket/$1 to current branch
# Also works with multiple ticket numbers

echo -e "\e[33m***** Show tickets planio? [Y, n] \e[39m"
read -rsn1 response

if [ "$#" -eq 0 ]; then
    echo "\e[31mNo ticket number present, aborting!\e[39m";
    exit 1
else
	for var in "$@"
	do
	    git fetch && git pull && git merge origin/ticket/$var --no-ff --no-edit && git push;
		if [ "$response" == "y" ]; then
			planio "$var"
		fi
	done
fi

echo -e "\e[33m***** Cleanup merged tickets now? [Y, n] \e[39m"
read -rsn1 cleanup
if [[ $cleanup == "y" ]]; then
	git cleanup
fi