#!/bin/bash

# Merge branch to slave branch and delete it afterwards
# If ticket number is parsed as param, try to merge ticket/$1 to slave
# If no param is passed, try to merge current branch.

git checkout dev && git fetch && git pull && git checkout slave && git pull && git merge dev --no-ff && git push &&
git checkout master && git pull && git merge slave --no-ff && git push && git checkout dev;