#!/bin/bash

# Check out ticket with passed #number

((!$#)) && echo No branch name, command ignored! && exit 1

git fetch;
echo ticket/$1;

[ ${#} -ne 1 ] && { echo -e "Please provide one search string" ; exit 1 ; }
MATCHES=( $(git branch -a --color=never | sed -r 's|^[* ] (remotes/origin/)?||' | sort -u | grep -E "^((ticket|release)/)?([A-Z]+-[1-9][0-9]*-)?${1}") )
case ${#MATCHES[@]} in
  ( 0 ) echo "No branches matched '${1}'" ; exit 1  ;;
  ( 1 ) git checkout "${MATCHES[0]}"      ; exit $? ;;
esac
echo "Ambiguous search '${1}'; returned ${#MATCHES[@]} matches:"

for ITEM in "${MATCHES[@]}" ; do
  echo -e "  ${ITEM}"
done
exit 1

echo -e "\e[33m***** Stop tracking in planio? [Y, n]"
read -rsn1 stop
if [ "$stop" == "y" ]; then
    opn https://webfactor.plan.io/stop_timer
fi

echo -e "\e[33m***** Start tracking in planio? [Y, n]"
read -rsn1 track
if [ "$track" == "y" ]; then
    opn https://webfactor.plan.io/issues/$1/start_timer
fi

