#!/bin/bash

# Remove branch locally and on origin.

((!$#)) && echo No branch name, command ignored! && exit 1

for var in "$@"
do
    git branch -d ticket/$var;
    git push origin --delete ticket/$var;
done