#!/bin/bash

# Merge branch to dev branch and delete it afterwards
# If ticket number is parsed as param, try to merge ticket/$1 to dev
# If no param is passed, try to merge current branch.

# Set excluded branches
excludedBranches="(^\*|master|slave|dev|alpha|beta|release)"

if [ "$#" -eq 0 ]; then
    branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p');
    ticketNumber=${branch:7};

    if [ -z "$ticketNumber" ]; then
        echo "No ticket number present, aborting!";
    else
        git checkout master && git fetch && git pull && git merge $branch && git push;
    fi
else
	for var in "$@"
	do
	    git checkout master && git fetch && git pull && git merge origin/ticket/$var && git push;
	done
fi
