#!/bin/bash

# Merge branch to dev branch and delete it afterwards
# If ticket number is parsed as param, try to merge ticket/$1 to dev
# If no param is passed, try to merge current branch.

# Set excluded branches
excludedBranches="(^\*|master|slave|dev|alpha|beta|release)"

if [ "$#" -eq 0 ]; then
    echo "A target release version must be provided."
    exit 0
elif [ "$#" -eq 1 ]; then
    branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p');
    ticketNumber=${branch:7};

    if [ -z "$ticketNumber" ]; then
        echo "No ticket number present, aborting!";
    else
        git checkout dev && git fetch && git pull && git merge $branch && git push;
    fi
else
    echo "TODO: Pass ticket numbers of branches-to-merge as params"
	# for var in "$@"
	# do
	#     git checkout dev && git fetch && git pull && git merge origin/ticket/$var && git push;
	# done
fi
