#!/bin/bash

# Checkout dev branch, fetch & pull, create new branch in ticket/#1

((!$#)) && echo No branch name, command ignored! && exit 1

git checkout dev && git fetch && git pull && git checkout -b ticket/$1

echo -e "\e[33m***** Stop tracking in planio? [Y, n]"
read -rsn1 stop
if [ "$stop" == "y" ]; then
    opn https://webfactor.plan.io/stop_timer
fi

echo -e "\e[33m***** Start tracking in planio? [Y, n]"
read -rsn1 start
if [ "$start" == "y" ]; then
    opn https://webfactor.plan.io/issues/$1/start_timer
fi
