#!/bin/bash

# Merge branch to dev branch and delete it afterwards
# If ticket number is parsed as param, try to merge ticket/$1 to dev
# If no param is passed, try to merge current branch.

# Set excluded branches
excludedBranches="(^\*|master|slave|dev|alpha|beta|release)"
edit="--no-edit"
ff="--no-ff"

for var in "$@"
do
	shift
	if [[ $var == "--ff" ]]; then
		ff=''
		echo "Will merge with fast forward."
	elif [[ $var == "--edit" ]]; then
		edit=''
		echo "Will show edit merge dialog."
	else
		set -- "$@" "$var"
	fi
done

if [ "$#" -eq 0 ]; then
    branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p');
    ticketNumber=${branch:7};

    if [ -z "$ticketNumber" ]; then
        echo "No ticket number present, aborting!";
    else
        git checkout master && git fetch && git pull && git merge $branch $ff $edit;
    fi
else
	for var in "$@"
	do
	    git checkout master && git fetch && git pull && git merge origin/ticket/$var $ff $edit;
	done
fi
