#!/bin/bash

# Initialises cloned laravel project

# Setup .env:
cp .env.example .env;

directory=${PWD##*/} ;
database=${directory//[-. ]/_}

mysql -uroot -p -e "CREATE DATABASE $database"
sed -i 's|DB_USERNAME=homestead|DB_USERNAME=root|g' .env
sed -i 's|DB_USERNAME=webfactor|DB_USERNAME=root|g' .env
sed -i 's|DB_PASSWORD=secret|DB_PASSWORD=|g' .env
sed -i "s|DB_DATABASE=database|DB_DATABASE=$directory|g" .env
sed -i "s|DB_DATABASE=webfactor|DB_DATABASE=$directory|g" .env
sed -i "s|DB_DATABASE=homestead|DB_DATABASE=$directory|g" .env
sed -i "s|DB_DATABASE=database|DB_DATABASE=$directory|g" .env
sed -i "s|DB_DATABASE=laravel|DB_DATABASE=$directory|g" .env
sed -i "s|APP_URL=http://localhost|APP_URL=https://$directory.test\nAPP_DOMAIN=$directory.test|g" .env
sed -i "s|APP_URL=https://webfactor.test|APP_URL=https://$directory.test\nAPP_DOMAIN=$directory.test|g" .env
sed -i "s|MAIL_USERNAME=null|MAIL_USERNAME=f0adaab8ee450d|g" .env
sed -i "s|MAIL_PASSWORD=null|MAIL_PASSWORD=dc72582ff97109|g" .env


# Setup dependency & data related stuff.
composer install && php artisan key:generate && php artisan migrate:fresh && php artisan db:seed && yarn && yarn dev && valet secure
php artisan jwt:secret
