#!/bin/bash

# Initialises cloned laravel project

# Setup .env:
cp .env.example .env;

directory=${PWD##*/};

mysql -uroot -p -e "CREATE DATABASE $directory"
sed -i 's|DB_USERNAME=homestead|DB_USERNAME=root|g' .env
sed -i 's|DB_PASSWORD=secret|DB_PASSWORD=|g' .env
sed -i "s|DB_DATABASE=homestead|DB_DATABASE=$directory|g" .env
sed -i "s|APP_URL=http://localhost|APP_URL=http://$directory.test\nAPP_DOMAIN=$directory.test|g" .env

# Setup dependency & data related stuff.
composer install && php artisan key:generate && php artisan migrate:fresh && php artisan db:seed
php artisan jwt:secret
yarn && yarn dev