#!/bin/bash

# Gradle helper script
# Params:
# 	- App flavor.
#	- These must be prefixed with a '-' and can be combined
#	  (e.g. -bri to build a release apk and deploy it to the device).
#		b -> Build new apk
#		i -> Install apk to device
#		r -> Use release apk
#		d -> Uninstall existing apk
#		o -> Open apk folder
#

flavor=""
build=false
variant="debug"
deploy=false
delete=false

# Goto mt-directory, if no params are passed.
if [[ $# == 0 ]]; then
	mehrtanken;
	exit 1;
fi


for var in "$@"
do
	if [[ ${var:0:1} == "-" ]]; then
		if [[ $var == *"b"* ]]; then
			build=true;
    		printf "****** Build new apk\n";
		fi
		if [[ $var == *"r"* ]]; then
			variant="release";
    		printf "****** Build variant: Release\n";
		fi
		if [[ $var == *"d"* ]]; then
	    	delete=true;
			printf "****** Delete existing apk \n";
		fi
		if [[ $var == *"i"* ]]; then
	    	deploy=true;
	    	printf "****** Install to device\n";
	    fi
		if [[ $var == *"o"* ]]; then
	    	open ./app/apk; xdg-open ./app/apk
	    fi
	else
		flavor=$var;
		printf "****** Flavor: $flavor\n";
	fi
done

Flavor="$(tr '[:lower:]' '[:upper:]' <<< ${flavor:0:1})${flavor:1}"
Variant="$(tr '[:lower:]' '[:upper:]' <<< ${variant:0:1})${variant:1}"

if [[ $build == true ]]; then
	./gradlew assemble$Flavor$Variant
fi

if [[ $delete == true ]]; then
	if [[ $Flavor != "" ]]; then
		echo Uninstalling ./app/build/outputs/apk/app-$flavor-$variant.apk
		./gradlew uninstall$Flavor"Release" uninstall$Flavor"Debug"
	else
		echo Uninstalling all app flavors
		./gradlew uninstallFreeDebug uninstallFreeRelease uninstallPaidDebug uninstallPaidRelease
	fi
fi

if [[ $deploy == true ]]; then
	if [[ $Flavor != "" ]]; then
		echo Installing ./app/build/outputs/apk/app-$flavor-$variant.apk
		./gradlew install$Flavor$Variant
	else
		echo "Installing paid and free flavor."
		./gradlew installPaid$Variant installFree$Variant
	fi
fi