#!/bin/bash

integerRegex='^[0-9]+$';

if [ "$#" -eq 0 ]; then
    branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p');
    ticketNumber=${branch:7};

    if [ -z "$ticketNumber" ]; then
		BASEDIR="$HOME"

		data=$(cat $BASEDIR/forge_data.json | jq .$key)
    	key=$(cat forge_data.json | jq '.key')
		planio=$(echo $data | jq .$key.planio | tr -d '"')
		if [[ $planio == null ]]; then
			planio=$key
		fi
		url=https://webfactor.plan.io/projects/$planio/issues?query_id=1pl 25
    else
		url=https://webfactor.plan.io/issues/$ticketNumber
    fi

else
if [[ $1 =~ $integerRegex ]] ; then
	ticketNumber=$1
	url=https://webfactor.plan.io/issues/$ticketNumber
else
	projectName=$1
	if [[ $projectName == 'mta' ]] ; then
		projectName='mehr-tanken';
	fi
	url=https://webfactor.plan.io/projects/$projectName/issues?query_id=125
fi
fi

	if [[ "$OSTYPE" == "linux-gnu" ]]; then
		xdg-open $url &!
		disown
	else
		open $url &!
	disown
fi
