#!/bin/bash

if [ "$#" -eq 0 ]; then
    branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p');
    ticketNumber=${branch:7};

    if [ -z "$ticketNumber" ]; then
		BASEDIR="$HOME"

		data=$(cat $BASEDIR/forge_data.json | jq .$key)
    	key=$(cat forge_data.json | jq '.key')
		planio=$(echo $data | jq .$key.planio | tr -d '"')
		if [[ $planio == null ]]; then
			planio=$key
		fi
		url=https://webfactor.plan.io/projects/$planio/issues?query_id=168
    else
		url=https://webfactor.plan.io/issues/$ticketNumber
    fi

else
	ticketNumber=$1
	url=https://webfactor.plan.io/issues/$ticketNumber
fi

	if [[ "$OSTYPE" == "linux-gnu" ]]; then
		xdg-open $url &!
		disown
	else
		open $url &!
	disown
fi
