#!/bin/bash

# run ionic app on android and ios device.
# (proxy is used in camigolo; add-proxy and remove-proxy can be found in the project's gulpfile)

gulp;
gulp remove-proxy;
ionic run android --device;
ionic run ios --device;
gulp add-proxy;