#!/bin/bash

#run ionic app on android device.
# (proxy is used in camigolo; add-proxy and remove-proxy can be found in the project's gulpfile)

gulp;
gulp remove-proxy;
ionic run android --device;
gulp add-proxy;