#!/bin/bash

if [ "$#" -eq 2 ]; then
	git clone -b dev git@webfactor.plan.io:webfactor/$1 $2;
	cd $2;
else
    echo "Illegal number of parameters. First param: remote name. Second param: desired local name";
fi