#!/bin/bash

# Possible params:
# '--alpha' (for alpha server; set by default)
# '--beta' (for beta (devactor) server)
# '--prod', or '--production' (for live-server)
# Any $key that is available in forge_data.json

BASEDIR="$HOME"
environment=alpha
ssh=false
key=null

for var in "$@"
do
    echo "Param: $var"

    if [[ $var == "--list" ]]; then
        data=$(cat $BASEDIR/forge_data.json | jq .)
        echo "Available data for deployment:"
        echo $data | jq .
        exit 0;
    elif [[ $var == "--keys" ]]; then
        data=$(cat $BASEDIR/forge_data.json | jq .)
        echo "Available data for deployment:"
        echo $data | jq 'keys'
        exit 0;
    elif [[ $var == "--prod"* ]]; then
        environment=production
        echo "Environment set to $environment"
    elif [[ $var == "--beta" ]]; then
        environment=beta
        echo "Environment set to $environment"
    elif [[ $var == "--alpha" ]]; then
        environment=alpha
        echo "Environment set to $environment"
    elif [[ $var == "--ssh" ]]; then
    	ssh=true
    else
        key=$var
        echo "Key set to $key"
    fi
done

if [[ $key == null ]]; then
    key=$(cat forge_data.json | jq '.key')
fi

if [[ $key == null ]]; then
    echo -e "\e[91m***** Cannot find project key. Please pass it either as a param, or store it in the project directory, in forge_data.json: {"key": "{PROJECT KEY}"}"
    exit 0;
fi

path=$key.$environment

data=$(cat $BASEDIR/forge_data.json | jq ".$key")

if [[ $data == null || $data == "" ]]; then
    echo -e "\e[91mCannot find data for key \e[1m$key\e[21m."
    exit 0
fi

echo "Data found:"
echo $data | jq .
echo

server_id=$(echo $data | jq .$environment.server_id)
server_ip=$(echo $data | jq .$environment.server_ip)
server_name=$(echo $data | jq .$environment.server_name)
site_id=$(echo $data | jq .$environment.site_id)
root=https://$(echo $data | jq .$environment.root | tr -d '"')

if [[ $server_id == null || $server_id == "" ]]; then
    echo -e "\e[91mCannot find $environment server-id for key \e[1m$key\e[21m."
    exit 0
fi

if [[ $site_id == null || $site_id == "" ]]; then
    echo -e "\e[91mCannot find $environment site-id for key \e[1m$key\e[21m."
    exit 0
fi

echo -e "\e[33m***** Start \e[1m$environment\e[33m deployment on\e[34m $root\e[33m now? [Y, n]"
read -rsn1 response
if [ "$response" == "y" ]; then
    forge deploy:site $server_id $site_id
    echo "Deploying... *****"
    echo -e "\e[33m***** Open forge page in browser? [Y, n]"
	read -rsn1 openForge
	if [ "$openForge" == "y" ]; then
		opn "https://forge.laravel.com/servers/$server_id/sites/$site_id#/application"
	fi

    echo -e "\e[33m***** Open project page in browser? [Y, n]"
	read -rsn1 openProject
	if [ "$openProject" == "y" ]; then
		opn "$root"
	fi
else
    echo "Aborted. *****"
fi

if [ "$ssh" == true ]; then
    echo -e "\e[33m***** SSH onto server ($server_name)? [Y, n]"
	read -rsn1 ssh
	if [ "$ssh" == "y" ]; then
		ssh "forge@$server_ip"
	fi
fi
